version: '3.8'
services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

  app:
    build: ../app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app:3001

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  